### ISSUE TITLE
Don't use MD5 Authentication for Users

### ISSUE THREAD

**Issue by jezell** [telepat-io/telepat-api#2]
https://github.com/telepat-io/telepat-api/blob/master/controllers/user.js#L203

MD5 is generally considered insecure for hashing passwords. It's way too easy to brute force and generate billions of hashes per second. Have you considered using something like bcrypt or scrypt instead?

**Comment by Mayhem93** [comment]
It uses md5+sha256+password salt

**Comment by jezell** [comment]
SHA-256 is a message hashing algorithm and is not really suitable for hashing passwords:
http://security.stackexchange.com/questions/90064/how-secure-are-sha256-salt-hashes-for-password-storage

**Comment by Mayhem93** [comment]
@jezell will switch over to bcrypt (https://www.npmjs.com/package/bcrypt) and will be available in the next release (should be at the end of next week).

**Comment by Mayhem93** [comment]
@jezell will replace this with bcrypt (https://www.npmjs.com/package/bcrypt) in the next release which will (hopefully) be at the end of next week.

**Comment by Mayhem93** [comment]
Commited on develop branch. Haven't tested it yet.

**Comment by Mayhem93** [comment]
Tested and closed.
