### ISSUE TITLE
Can not create application

### ISSUE THREAD

**Issue by rickyngk** [telepat-io/telepat-api#3]
Hello,
I'm using telepat 0.2.x via Docker on MacOS. Now I can not create new application by using "/admin/add/app"

    Error returns: "Error: Not Found\n    at /u…ypes/urlencoded.js:77:44"

I can not create application via ./telepat.sh also. When I create with option 3 (3. Create a new app), no error returns but no app created. For option 4 (4. Create a new app with a sample schema), another error returns

    {"status":400,"stack":"SyntaxError: Unexpected token s\n    at Object.parse (native)\n    at parse (/usr/src/app/node_modules/body-parser/lib/types/json.js:84:17)\n    at /usr/src/app/node_modules/body-parser/lib/read.js:102:18\n    at done (/usr/src/app/node_modules/body-parser/node_modules/raw-body/index.js:248:14)\n    at IncomingMessage.onEnd (/usr/src/app/node_modules/body-parser/node_modules/raw-body/index.js:294:7)\n    at IncomingMessage.g (events.js:199:16)\n    at IncomingMessage.emit (events.js:104:17)\n    at _stream_readable.js:908:16\n    at process._tickCallback (node.js:355:11)","message":"Unexpected token s"}

**Comment by Mayhem93** [comment]
*Error: Not Found\n* is an error returned by express.js when a route has not been found. The old documentation has not been updated yet on the website. The correct route is `POST /admin/app/add` .

Also you should always specify the "x" in *0.2.x* version name because there are a lot of changes from version to version.

@gabidobo Take a look at telepat-cli.

**Comment by rickyngk** [comment]
Thank for your info. Now I'm working on 0.2.2
After pull https://github.com/telepat-io/telepat-docker-compose-files again, I see that couchbase removed and I can not start application anymore. I add couchbase back from my side.

Then issue still happens.

    App name: test01
    API Key: 81dc9bdb52d04dc20036dbd8313ed055
    Logging in...
    Got JWT: content
    Adding app...
    Created app with ID: status

    Done. Anything else?
    1. Change Telepat API endpoint
    2. Create a new administrator account
    3. Create a new app
    4. Create a new app with a sample schema
    5. Done

But no record created in db 
<img width="958" alt="screen shot 2015-09-21 at 4 04 22 pm" src="https://cloud.githubusercontent.com/assets/6576523/9988404/7840c66e-607a-11e5-9b26-8f4d0e0994e7.png">

**Comment by Mayhem93** [comment]
With the release of version 0.2.3 we've replaced couchbase with ElasticSearch. The bugs you're having should be fixed by now.

**Comment by andreimarinescu** [comment]
Closing this as there was no further activity.
