### ISSUE TITLE
Fatal error:  [Error: not_found: Design document _design/dev_models not found]

### ISSUE THREAD

**Issue by mingfang** [telepat-io/telepat-api#4]
Getting this on a fresh install during startup.
Full log
```
./bin/www
Connected to Data bucket on couchbase.
Client connected to Redis.
Connected to Elasticsearch.
Waiting for Zookeeper connection...
Client connected to Zookeeper.
Fatal error:  [Error: not_found: Design document _design/dev_models not found]
```

**Comment by Mayhem93** [comment]
What version/build are you using? Are you using the docker containers ?

**Comment by Mayhem93** [comment]
We also replaced couchbase with elasticsearch in our latest release (0.2.3).

The Docker containers will be updated later today.

**Comment by mingfang** [comment]
I just upgraded to v0.2.3.
But now I'm getting this
```
./bin/www
Missing environment variable "TP_KFK_HOST". Trying configuration file.
Missing environment variable "TP_ES_HOST". Trying configuration file.
Connected to ElasticSearch MainDatabase
Client connected to Redis.
Waiting for Zookeeper connection...
Client connected to Zookeeper.
Fatal error:  { [Error: IndexMissingException[[default] missing]]
  status: '404',
  message: 'IndexMissingException[[default] missing]' }
```

I am make my own Dockerfile.

**Comment by Mayhem93** [comment]
Ok, well I know this isn't specified anywhere (I will include it in the docs sometime). But you need to create the index first (also make sure the index is correct in the config file / env vars).

You need to create the index with dynamic mappings, like so: 

    PUT /index
    {
        "mappings": {
            "_default_": {
                "dynamic_templates": [
                    {
                        "string_template": {
                            "mapping": {
                                "index": "not_analyzed",
                                "type": "string"
                            },
                            "match_mapping_type": "string",
                            "match": "*"
                        }
                    }
                ]
            }
        },
        "settings": {
            "index": {
                "number_of_replicas": "1",
                "number_of_shards": "1"
            }
        }
    }

**Comment by mingfang** [comment]
@Mayhem93 Thanks.
This works.

**Comment by mingfang** [comment]
If anyone is interested, my Dockerfiles for the API and all the workers are available here.
https://github.com/mingfang/docker-telepat-api.git
https://github.com/mingfang/docker-telepat-worker.git
