### ISSUE TITLE
Can not delete application

### ISSUE THREAD

**Issue by rickyngk** [telepat-io/telepat-api#5]
I'm using Telepat 0.2.2 from docker
"Context is not defined" error occurred when remove app
http://docs.telepat.io/api.html#api-Admin-AdminAppRemove

    "{"status":500,"stack":"ReferenceError: Context is not defined\n at /usr/src/app/node_modules/telepat-models/lib/Application.js:211:4\n at fn (/usr/src/app/node_modules/async/lib/async.js:752:34)\n at /usr/src/app/node_modules/async/lib/async.js:1252:16\n at /usr/src/app/node_modules/async/lib/async.js:697:43\n at Object.async.waterfall (/usr/src/app/node_modules/async/lib/async.js:701:44)\n at Function.Application.delete (/usr/src/app/node_modules/telepat-models/lib/Application.js:209:8)\n at /usr/src/app/controllers/admin.js:346:27\n at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:82:5)\n at next (/usr/src/app/node_modules/express/lib/router/route.js:110:13)\n at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:91:3)\n at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:82:5)\n at /usr/src/app/node_modules/express/lib/router/index.js:267:22\n at Function.proto.process_params (/usr/src/app/node_modules/express/lib/router/index.js:321:12)\n at next (/usr/src/app/node_modules/express/lib/router/index.js:261:10)\n at security.adminAppValidation (/usr/src/app/controllers/security.js:121:2)\n at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:82:5)","message":"Context is not defined"}"

**Comment by Mayhem93** [comment]
This issue has ben fixed in the latest release.
