### ISSUE TITLE
Suggestion: admin_id of blg:applications should be protected

### ISSUE THREAD

**Issue by rickyngk** [telepat-io/telepat-api#6]
Telepat 0.2.2

When I use this api (http://docs.telepat.io/api.html#api-Admin-AdminAppUpdate) without post admin_id, I lost my application. Check in Couchbase console, I see that admin_id was removed

**Comment by Mayhem93** [comment]
In the latest build `/admin/app/update` only works with patches. So the only reason `admin_id` could disappear (or have invalid data) would be because of a malicious request. 

I do agree we should have protected properties on the built in models.

**Comment by rickyngk** [comment]
Thank for you info.
