### ISSUE TITLE
Facebook Login/Registration Questions

### ISSUE THREAD

**Issue by aaronfranco** [telepat-io/telepat-api#8]
When a new users attempts to register with Facebook, the system attempts to collect their Facebook Friends list.
The code performing this action on line 227 in Users controller.
````
if (accessToken) {
	FB.napi('/me/friends', {access_token: accessToken}, function(err, result) {
		if (err) return callback(err);
			for(var f in result.data) {
				fbFriends.push(result.data[f].id);
				}
					callback();
				});
} else
      callback();
````
A typical FB request will only return a certain number of results. I think the maximum is 20 results per page. For a user with 500 friends, 25 requests would have to be made to FB to collect their entire friend list. Therefore, this bit of code is incomplete.

What is the thinking behind getting the user's Facebook friend list upon registration?

Does the API really need to do this?

Food for thought :)

**Comment by andreimarinescu** [comment]
The API does this in preparation of a more social layer of filters. Actually, your thoughts on this would be nice. The ideea here is that we can keep a list of friends updated, and internally know if a telepat user is a friend of another telepat user. 

That would enable you to subscribe to stuff like "your friends' comments on post X".

We found that to be an interesting use-case, however there doesn't seem to be a lot of consensus on that, so we might drop this in the future.

**Comment by aaronfranco** [comment]
Telepat is an infrastructure tool for building scalable apps not a social platform. As a developer, I could build a blogging app that tells my users if a friend commented on their post. The reason I choose Telepat as my infrastructure is because it scales as my user base scales. I think the focus should be on scalability, reliability and performance.

**Comment by andreimarinescu** [comment]
I agree, this is more of a remnant from a time we had a much more narrow approach to the things we could do with Telepat. 
Since this is starting to cause more issues than functionality, we'll move to dropping this from the codebase. I'm adding a ticket on our issue tracker on this right now.

**Comment by aaronfranco** [comment]
:+1:
